{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidylog
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidylog_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidylog/tidylog_{{ version }}.tar.gz
  sha256: 71275df6157b1242cf0a222e1834e9e94df49d10143dd1e6c007ea79b7027719

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-clisymbols
    - r-dplyr
    - r-glue
    - r-tidyr
  run:
    - r-base
    - r-clisymbols
    - r-dplyr
    - r-glue
    - r-tidyr

test:
  commands:
    - $R -e "library('tidylog')"           # [not win]
    - "\"%R%\" -e \"library('tidylog')\""  # [win]

about:
  home: https://github.com/elbersb/tidylog/
  license: MIT
  summary: Provides feedback about 'dplyr' and 'tidyr' operations.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tidylog
# Type: Package
# Title: Logging for 'dplyr' and 'tidyr' Functions
# Version: 0.2.0
# Authors@R: person("Benjamin", "Elbers", email = "elbersb@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-5392-3448"))
# Description: Provides feedback about 'dplyr' and 'tidyr' operations.
# License: MIT + file LICENSE
# Imports: dplyr, tidyr, glue, clisymbols
# Suggests: testthat, covr, lintr
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/elbersb/tidylog/
# BugReports: https://github.com/elbersb/tidylog/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-02 15:39:57 UTC; benjamin
# Author: Benjamin Elbers [aut, cre] (<https://orcid.org/0000-0001-5392-3448>)
# Maintainer: Benjamin Elbers <elbersb@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-02 16:10:02 UTC
