appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fx9a4r2MVgMGas7b1gNdfD3lnD0780njxuG7u5C+XgnT4jqV/4Djp2W1oppEcFV169X+9Z2vdS5SRnZNuebEUi/wwscpGC08HF3KTw0+ZgPPvo4tUnBt8JSNtzEY7dfqIJWaXlbjaglDjhdJ9jaaxTaUeUsk36cJ2VoyVtfWOQgLbyV6Yw/ruG77NZDmbr113Nt+haxre+P6rtAdB+sSzfR2g05xqCAlgZgEK93hf17X/yhdRlWghAsk9ZNAC3c/ApC+JOMvcna4Cq7epT36IfBluaAkee20IgFY5YFqwwM+5kxgBdsaFamPxrwY+Ua4Kz3X1dlvDc5/+Mjxda710uCYxYQ9KXl2x4eYXdHJ9ru1Cq7T8+/kuXu1WfLjSPvY4oUdoi2zBdTmhmzI/WIaGSNm2eX+GPbwyoA22Imk/MZiH2Vta4ssK0Qil4Wsr5i/bSutLltKCBxmLKO1CRY91sAS0czbsyKz/xgp/Sa6fIIBjkm2WrAy+32nhKYatQr/rtx1cy2IVmJGuMVaHRECEo9APa+MEW2eUo7nsChPJbaZ8aKfelQ70P5dxMNm53eR8orLNomZNqoxts8NEwtVA7i+qkC9d9iKlYiy5lj1uiKAXVeD5hIA+wgSffTxnV6WoXi/p7adXAbRzzNwFCdCcw/KIhpEzxRVUBly4CBwqco=
